name: Daily Green Square

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:    # Allows you to click a button to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Date File
        run: echo "$(date)" >> last_run.txt
        
      - name: Commit and Push
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Green Square Bot"
          git add last_run.txt
          git commit -m "Daily Green Square Update"
          git push
